version: '3.7'
services:
    api:
        container_name: api
        build: 'api/'
        volumes:
            - ./modeling/src:/workdir/src
            - ./api:/workdir/api
            - ./data/raw:/workdir/data/raw
        ports:
            - "5000:5000"
        command: "python3 /workdir/api/server.py"

    modeling:
        container_name: modeling 
        build: 'modeling/'
        volumes:
            - ./modeling/bin:/workdir/bin
            - ./modeling/src:/workdir/src
            - ./data/raw:/workdir/data/raw
            - ./tensorboard_logs:/workdir/tensorboard_logs
        command: "tail -f /dev/null"
        environment:
            - DISPLAY=host.docker.internal:0
            
    tensorboard:
        container_name: tensorboard
        build: 'tensorboard/'
        volumes:
            - ./tensorboard_logs:/workdir/tensorboard_logs
        command: 'tensorboard --logdir /workdir/tensorboard_logs --bind_all'
        ports: 
            - "6006:6006"
            