FACE_DETECTION_MODEL_PATH = "/workdir/src/models/face_detection/face_detection_slim.tflite"
DEMO_IMAGE_FILE = "/workdir/data/raw/face_input.jpg"
CHECKPOINTS_PATH = "/workdir/tensorboard_logs/BasicCNNModel/demo_model/checkpoints/save.ckpt"
FACIAL_KEYPOINTS_PATH = "/workdir/data/raw/facial_keypoints.csv"
FACE_IMAGES_PATH = "/workdir/data/raw/face_images.npz"
TENSORBOARD_LOG_DIR = "/workdir/tensorboard_logs"
OUTPUT_FILE = "/workdir/data/raw/output.jpg"
